### ISSUE TITLE
write function for time series datastore

### ISSUE THREAD

**Issue by jcolley** [me-box/lib-python-databox#6]
Given that nearly all of the working drivers at the moment handle time series data, we need read and write functions for time series data stores. At the moment I can only see key-value stores supported in by the library.

**Comment by pooyadav** [comment]
Yes,  the current time -series data store is going to be replaced by the new store (by @jptmoore ) - so python api will be available soon.

**Comment by jcolley** [comment]
I appreciate that but the current release of data box does not support the new datastore yet, for now there should be support for all *current* data stores and then if these methods need to be deprecated at a later stage then thats OK.

**Comment by mor1** [comment]
@jcolley PRs welcome :) More usefully, @jptmoore do we have an ETA for the new store yet?

**Comment by Toshbrown** [comment]
@mor1 I'm looking at integration today, not sure what we will find along the way so can't give a firm timeframe

**Comment by pooyadav** [comment]
@mor1  @jcolley  I'll create a PR today for the current time-series, just in testing mode.

**Comment by jptmoore** [comment]
@mor1 the protocol design should be static enough now to build a client against the server and also run within databox. @pooyadav it might be a good idea to start work on the protocol in python.

**Comment by jcolley** [comment]
Is there an estimate on either the new store being available (with python support) or the python library supporting the time series store please.

**Comment by pooyadav** [comment]
Resolved by https://github.com/me-box/lib-python-databox/pull/8 & https://github.com/me-box/lib-python-databox/pull/10
